// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("GeneralComments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedDays")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ApplicantId", "Status");

                    b.ToTable("LeaveApplications", (string)null);
                });

            modelBuilder.Entity("Api.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDaysAllowed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LeaveType", "Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MaxDaysAllowed = 20,
                            Name = "annual"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MaxDaysAllowed = 7,
                            Name = "sick"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MaxDaysAllowed = 3,
                            Name = "emergency"
                        });
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "jane.doe@example.com",
                            FullName = "Jane Doe",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKmyBZSOdiRCMd5DIuHtL0bfJ4gHH+CaF1tfDxKSrGczzKlfmYrk66lRfODdGYRQAQ==",
                            Role = "Employee",
                            Username = "jdoe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "john.smith@example.com",
                            FullName = "John Smith",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKmyBZSOdiRCMd5DIuHtL0bfJ4gHH+CaF1tfDxKSrGczzKlfmYrk66lRfODdGYRQAQ==",
                            Role = "Employee",
                            Username = "jsmith"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "maria.santos@example.com",
                            FullName = "Maria Santos",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKmyBZSOdiRCMd5DIuHtL0bfJ4gHH+CaF1tfDxKSrGczzKlfmYrk66lRfODdGYRQAQ==",
                            Role = "Employee",
                            Username = "msantos"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "robert.hale@example.com",
                            FullName = "Robert Hale",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKmyBZSOdiRCMd5DIuHtL0bfJ4gHH+CaF1tfDxKSrGczzKlfmYrk66lRfODdGYRQAQ==",
                            Role = "Manager",
                            Username = "rhale"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "priya.nair@example.com",
                            FullName = "Priya Nair",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKmyBZSOdiRCMd5DIuHtL0bfJ4gHH+CaF1tfDxKSrGczzKlfmYrk66lRfODdGYRQAQ==",
                            Role = "Manager",
                            Username = "pnair"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "david.kim@example.com",
                            FullName = "David Kim",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEKmyBZSOdiRCMd5DIuHtL0bfJ4gHH+CaF1tfDxKSrGczzKlfmYrk66lRfODdGYRQAQ==",
                            Role = "Manager",
                            Username = "dkim"
                        });
                });

            modelBuilder.Entity("Api.Models.LeaveApplication", b =>
                {
                    b.HasOne("Api.Models.User", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.LeaveType", "LeaveType")
                        .WithMany("Applications")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.User", "Manager")
                        .WithMany("ManagedApplications")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("LeaveType");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Api.Models.LeaveType", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ManagedApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
